Wandbot zd
wandb/wandbot pull request #44
Opened 2023-10-24 23:06 UTC by ArtsiomWB

Calls ZenPy api in order to fetch zendesk tickets from discourse, process them and feed them through wandbot API. Then get a response and post it privately in Zendesk under the ticket that had that question. 

Latest Changes:
Added my script, changed all of the print statements in to logger that you use in slack app. 

I have not added my app to the `run.sh` because I wanted to ask you what is the best way of going about it?
What does the .env look like in replit?

2023-10-26 07:03 UTC, parambharat requested changes
@ArtsiomWB. Thank you for the PR. This is a good start. I made some suggestions. Also, please merge the main branch into your branch to get the latest upstream changes.

2023-10-26 07:03 UTC, parambharat commented on src/wandbot/apps/ZD/ZDWandbot.py
> +            logger.info(f"New unanswered Tickets: {new_tickets}")
Maybe just log the number of unanswered tickets here. Logging a list of tickets with all their content can fill-up the logs making debugging harder.

2023-10-26 07:03 UTC, parambharat commented on src/wandbot/apps/ZD/ZDWandbot.py
> +load_dotenv()
This should be removed. We will not use a .env file in the deployment but instead store secrets in and env. See comment below on using a pydantic settings class for getting the secrets from the env.

2023-10-29 11:43 UTC, Dezzj reviewed
Veiwed

2023-10-30 23:35 UTC, ArtsiomWB commented
@parambharat, made the suggested changes and pulled main! :D

2023-10-31 02:35 UTC, Dezzj reviewed
Veiwed

2023-11-10 06:35 UTC, parambharat approved these changes
LGTM

2023-11-10 06:39 UTC, merged